-- TimescaleDB setup skipped: not available on Railway PostgreSQL
-- Hypertables and continuous aggregates require TimescaleDB extension
-- which must be installed at the PostgreSQL server level.
-- The application works without it using standard PostgreSQL tables.
